# Generated by Django 2.2.14 on 2020-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gdpr_helpers", "0003_auto_20200414_1324")]

    operations = [
        migrations.AlterField(
            model_name="legalreasongroup",
            name="where",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Posizione del gruppo"
            ),
        )
    ]
