# Generated by Django 2.2.19 on 2021-03-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_helpers', '0004_auto_20200717_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalreason',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
